informatikr/hedis

- src/Database/Redis/Core.hs
This PR derives a `Show` instance for `ConnectInfo`, which helps with debugging. My use case was checking code I had written to parse a config file to create a `ConnectInfo`.
Example usage:
```haskell
putStrLn $ "Default connectInfo:" ++ (show defaultConnectInfo)
```
which prints:
```
Default connectInfo:ConnInfo {connectHost = "localhost", connectPort = PortNumber 6379, connectAuth = Nothing, connectDatabase = 0, connectMaxConnections = 50, connectMaxIdleTime = 30s}
```
> Derive Show instance for ConnectInfo

- src/Database/Redis.hs
- src/Database/Redis/Core.hs
Lazy I/O used for automatic pipelining should not leak from runRedis calls. Otherwise it could lead to e.g. conflict with resource pool scope seen in #23 or exceptions being thrown in unexpected places (see e.g. #35)
To prevent this from happening now all replies up to the last should be received inside of `runRedis`.
As a breaking change this should trigger version bump and probably some announcement.
> Enforce all replies being recieved in runRedis

- src/Database/Redis/PubSub.hs
It appears to be asynchronous by nature but it could be unexpected
by library users
It addresses #28
> Added comments about Pub/Sub being async

- codegen/GenCmds.hs
- src/Database/Redis/Commands.hs
Added "Since" into the descriptions and removed occasional dots to make them more uniform.
#61 will need to be updated with these changes
> Haddock fixes

- hedis.cabal
- src/Database/Redis/Protocol.hs
- src/Database/Redis/ProtocolPipelining.hs
- stack-7.10.yaml
- stack-7.8.yaml
- stack-head.yaml
- stack.yaml
This PR is **not ready** for merging.
The existing parser is based on `attoparsec`. But it doesn't use backtracking, so all the bookkeeping that attoparsec does is unnecessary. This RP contains an initial implementation of non-backtracking incremental parser. In my measurements it is 2x faster then attoparsec. In hedis benchmark it shows ~10% performance improvement and noticeable decrease of memory allocations.
The code needs polishing, but before I invest more time, I'd like to know whether you are interested in integrating this into hedis.
Before:
```
ping                  172002.17 Req/s
get                   151622.67 Req/s
mget                  111870.34 Req/s
ping (pipelined)     1020304.05 Req/s
multiExec get 1       102920.15 Req/s
multiExec get 50      623344.24 Req/s
multiExec …
```
> Implement parser without backtracking

- src/Database/Redis.hs
- src/Database/Redis/Core.hs
Pull request for idea proposed in issue https://github.com/informatikr/hedis/issues/14, if agreeable.
Optionally exposes the `Redis` data constructors by importing `Database.Redis.Core`.
> Optionally expose Redis data constructors

- src/Database/Redis.hs
This allows users of this library to extend their own monads with the
`MonadRedis` class.
> Export MonadRedis constructors for liftRedis

- hedis.cabal
- src/Database/Redis/Core.hs
- src/Database/Redis/ProtocolPipelining.hs
- src/Database/Redis/PubSub.hs
- test/ManualPubSub.hs
- test/PubSubTest.hs
- test/Test.hs
To implement issue #49, add a new multithreaded Pub/Sub message processing feature.
I added extensive haddocks to describe how to use the new feature.
The main benefit over the existing Pub/Sub code (which is left unchanged) is:
- you can make subscription changes at any time
- you can safely recover from networking errors such as the redis servier dying
- you can detect when Redis has actually processed a subscription request and
handlers will now start receiving messages.
This likely also solves #39 since you can recover from connection failures, and while not directly implementing it, will allow the timeout in #7 since you can manually implement some timeout.
----
The design turned out to be relatively simple:
- There is a single thread which only reads messages from redis
- There is a …
> Add multithreaded Pub/Sub message processing

- codegen/GenCmds.hs
- src/Database/Redis/Commands.hs
For some reason we were explicitly not exporting constructors for
Condition. This appears to have made it actually impossible to use the
"Opts" variants of set, zadd and specify the conditions.
> Export all Condition constructors

- CHANGELOG
- src/Database/Redis/Core.hs
- src/Database/Redis/ProtocolPipelining.hs
It's useful at least as a way to differentiate between slow connection establishing and slow execution of required Redis commands (which e.g. could have larger time limits).
> Added connectTimeout option

- .travis.yml
- src/Database/Redis/ManualCommands.hs
- test/Test.hs
`srandmemberN` incorrectly specified its return type as `Maybe
ByteString`, when the point of it is to return a list of items. The
command always returns a multi bulk response even if you specify a
count of 0 or 1 or the key doesn't exist, so there is actually no way
to call this function and not get a `Left`. I have changed that to a
list and added a test to show it works.
> Return list from srandmemberN

- src/Database/Redis.hs
- src/Database/Redis/Core.hs
This is the minimal implementation. Basically it closes all handles of idle connection immediately instead of waiting for the `connectMaxIdleTime`.
I'm not sure how I can actually test this as I can't check for the number of connections inside the pool or so...
> Add disconnect which destroys all (idle) resources in the pool

- .travis.yml
- CHANGELOG
By using the 5.0 release, all the test cases for the streams based commands can pass.
> Fix travis

- src/Database/Redis.hs
- src/Database/Redis/Core.hs
- src/Database/Redis/ProtocolPipelining.hs
- src/Database/Redis/URL.hs
- stack-8.4.3.yaml
With these changes, the `connect` function will try to connect to all the candidate IP addresses for a given domain name until either it successfully connects one of them or fails to connect to all of them.
`PortID` used to be exposed in multiple places but got deprecated with the version 2.8.0.0 of `Network`. These changes replace `PortID` with the new `PortNumber` and therefore should probably be considered as breaking changes.
I made a new `stack-8.4.3.yaml` file and updated `stack.yaml` with a new version of the resolver but I'm not sure if this is the "correct way" to do it. Please let me know it should be done differently.
When running the tests for these changes, two of them failed; however, those also fail on the master branch on my computer. Can some one make sure all the tests …
> Updates for compatibility with Network-2.8.0.0

- hedis.cabal
- src/Database/Redis.hs
- src/Database/Redis/Core.hs
- src/Database/Redis/ProtocolPipelining.hs
- src/Database/Redis/URL.hs
ConnectInfo.connectPort now uses PortID product type again
> Bring back ability to connect via a Unix Socket

- hedis.cabal
Since the latest stable is now 5.0 and current hedis seems to be supporting it, I think we can change here too.
> Update redis latest stable version in the description

- .gitignore
- src/Database/Redis/ProtocolPipelining.hs
In #126, the use of `bracketOnError` in `hConnect'` was replaced with a  `catch` in `connectSocket`. Unfortunately, that `catch` comes after the call to `NS.socket`, so if an asynchronous exception happens after the call to `NS.socket`, but before entering the `catch` block, `NS.close` won't be called and the socket handle will leak. 
This PR fixes the problem, plus as a bonus there's also a small improvement to `getHostAddrInfo`. 
We had a problem in production after upgrading to `hedis-0.11` that was fixed by downgrading to `0.10`. We're still investigating it, but highly suspect that it was caused by the change in #126.
/cc @k-bx @arybczak
> Fix some asynchronous exception safety problems

- src/Database/Redis/Core.hs
`#if __GLASGOW_HASKELL__ >= 860` didn't match for GHC 8.6.x so we'd need to change it to `> 711`. I made this mistake myself in #138 so really sorry for not testing more carefully back then. I have tested this code in my own project now.
> fix MonadFail instance

- src/Database/Redis/Commands.hs
- src/Database/Redis/ManualCommands.hs
- src/Database/Redis/Types.hs
- test/Test.hs
Hi! Thanks for this useful library!
I had some issues with Redis `inf` arguments and found this [issue](https://github.com/informatikr/hedis/issues/119).
In this PR I implemented handling of infinity values for `Double` arguments, as it was discussed in issue.
Also, doubting i decided to add `inf` value constructor.
Tests are green, including new test for `zrange` API.
Any feedback welcome!
> Added support of +/- inf redis argument

- src/Database/Redis/ProtocolPipelining.hs
Originally, Hedis re-exported the `PortID` type from `Network`, and it derived `Eq` as well as `Show`.  The `Network` module was deprecated in `network 2.7.0.0` and then removed in `network 3.0.0.0`.  Hedis was updated to just use `PortNumber` (from `Network.Socket`), removing support for Unix sockets.  A `PortID` type was then added to Hedis in order to restore support for Unix sockets in [commit 9c218f1b504206d644f9ee65b9d603a7e9418076](https://github.com/informatikr/hedis/commit/9c218f1b504206d644f9ee65b9d603a7e9418076).  The new type does not derive `Eq`, but I think that the `Eq` instance was just forgotten.  I use the hostname and port to identify connections during failover, so it would be convenient to have an `Eq` instance.
> Add Eq instance to PortID

- hedis.cabal
- src/Database/Redis/Core.hs
- test/run-test.sh
withConnect has an embedded IO (i.e. `-> (a -> IO b) ->`) which is famously annoying for monad stacks.  We can generalize this really easily though using MonadMask from the exceptions package and lifting the connect/disconnect calls.
> Make withConnect friendly to transformer stack

- src/Database/Redis.hs
- src/Database/Redis/ProtocolPipelining.hs
The `ConnectTimeout` exception can be thrown, however is not exported, and not be specifically caught from the public API. This can happen during for example a `checkedConnect`.
This PR exposes the `ConnectTimeout` exception.
> Publicly expose ConnectTimeout exception

- .gitignore
- hedis.cabal
- src/Database/Redis.hs
- src/Database/Redis/Cluster.hs
- src/Database/Redis/Cluster/Command.hs
- src/Database/Redis/Cluster/HashSlot.hs
- src/Database/Redis/Commands.hs
- src/Database/Redis/Connection.hs
- src/Database/Redis/ConnectionContext.hs
- src/Database/Redis/Core.hs
- src/Database/Redis/ManualCommands.hs
- src/Database/Redis/ProtocolPipelining.hs
- src/Database/Redis/PubSub.hs
- src/Database/Redis/Transactions.hs
- src/Database/Redis/URL.hs
- stack.yaml
I've been working on implementing the client aspects of clustered Redis on behalf of Juspay. This is a first attempt, it's a proof of concept so it's not at all complete, but I wanted to get feedback from the community to check we're on the right path.
The main limitations at the moment are:
- It only handles commands where the first argument is a key
- It doesn't do any kind of pipelining.
- It isn't threadsafe
- It doesn't do any kind of connection pooling
None of these are in principle hard to fix, but I wanted to make sure that the general approach worked.
There were a few changes I had to make:
- Moved the `ConnectionContext` abstraction into it's own module `Database.Redis.ConnectionContext` so it could be shared between clustered and non clustered connections
- Moved the …
> WIP: Clustering Implementation

- src/Database/Redis/ManualCommands.hs
This was confusing me because the existing documentation suggested the first argument was the script itself, but the docs indicate that argument should contain the Base16-encoded SHA1 hash of the script.
I have a little wrapper function which accepts the script itself, and performs the encoding, but you might not like to add something like `cryptonite` as a dependency here?
See https://redis.io/commands/eval#bandwidth-and-evalsha
> Improved documentation for EVALSHA

- test/ClusterMain.hs
Since Redis Cluster doesn't support the SELECT command, `testConnectDb` and `testConnectDbUnexisting` are not suitable for `ClusterMain.hs` .
Actually, these tests use `defaultConnectInfo` internally and try to connect to the default Redis server instead of Redis Cluster working on port 7000.
> remove invalid tests for Redis Cluster

- src/Database/Redis/Cluster/Command.hs
Since Redis 6.0, it seems that `COMMAND` returns new 7th elements.
See https://github.com/redis/redis/pull/5836
> support for redis 6.0 COMMAND format

- hedis.cabal
This tells Cabal not to attempt building with GHC < 8.
Fixes #177.
> Record StrictData in other-extensions

- src/Database/Redis/Connection.hs
Related to #188, in lieu of a breaking API change.
> Document that UnixSocket ignores connectHost

- src/Database/Redis/Sentinel.hs
The upcoming `mtl-2.3.1` release will not re-export `MonadIO(liftIO)` from
unrelated modules. So let's add an additional (backwards compatible) import.
This keeps `hedis` working, even with the latest `mtl` release (which is currently not compatible).
Tested using the following `cabal.project`:
```
packages: .
constraints: mtl==2.3.1
```
> `mtl-2.3.1` compatibility

- CHANGELOG
- hedis.cabal
- src/Database/Redis/Commands.hs
- src/Database/Redis/ManualCommands.hs
- test/Main.hs
- test/MainRedis7.hs
- test/Tests.hs
In this MR we add a Redis 7 support for XINFO commands. And improve test-suite.
All changes are backwards compatible.
> Add Redis 7.0 compatibility 

- src/Database/Redis/Core.hs
Added `MonadTrans` transformer-based instace for `MonadRedis` to ease
its use in monad transformer stacks.
> Add `MonadTrans` instance for `MonadRedis`

- src/Database/Redis.hs
Make calling `sendRequest` a little easier by allowing to re-use hedis' `RedisArg` class.
> Expose RedisArg class to better support low-level sendRequest calls

- src/Database/Redis/Commands.hs
- src/Database/Redis/Connection.hs
- src/Database/Redis/ManualCommands.hs
- src/Database/Redis/URL.hs
- test/Main.hs
- test/Tests.hs
Introduce auth option that support passing username:
authOpts
Extend parseUrl function to parse username as well.
Fixes #199
> Add ability to use ACL

- src/Database/Redis/URL.hs
This commit restores pre-ACL  behaviour  when we could pass password without a username.
> fixed zero string input in connectUsername

- src/Database/Redis/Commands.hs
- test/Tests.hs
Using sadd and del requires to pass at least one parameter and it hurts users. So we change and API as it was discussed  in issue #44.
Fixes #44.
> Breaking change: change API of the sadd and del to accept NonEmpty lists

- src/Database/Redis/Commands.hs
- test/Tests.hs
Use NonEmpty in srem command because redis requires at least one member to be passed.
Fixes #175.
> Use Data.List.NonEmpty in srem command

- benchmark/Benchmark.hs
- src/Database/Redis/Commands.hs
- src/Database/Redis/ManualCommands.hs
- src/Database/Redis/Types.hs
- test/ClusterMain.hs
- test/Tests.hs
This PR provides a support for all functionality that appeared in Redis7, but only for already existing functions.
In addition safely was increased by using NonEmpty list where at least one argument is required by the protocolю
> Provide redis 7 support for all existing functions

- hedis.cabal
- src/Database/Redis.hs
- src/Database/Redis/Cluster.hs
- src/Database/Redis/Connection.hs
- src/Database/Redis/Core.hs
- src/Database/Redis/Hooks.hs
- src/Database/Redis/ProtocolPipelining.hs
- src/Database/Redis/PubSub.hs
- src/Database/Redis/PubSub.hs-boot
- test/MainHooks.hs
This PR introduce hooks. These hooks hook sending requests and receiving responses.
I am implementing an instrumentation of OpenTelemetry for Hedis. First I wrapped the Hedis functions to record for tracing, but it cause a lot of type mismatch because the original client and the wrappers have different types of course. So I want to use hooks to avoid this inconvenience.
- `ConnectInfo` has a new field `connectHooks`
- `Hooks` type is introduced
Currently there are five types of hooks:
- `sendRequest`
- `sendPubSub`
- `callback`
- `send`
- `receive`
`sendRequest` is called when a command is being sent. `sendPubSub` is called when a Pub/Sub message is being send. `callback` is called when a reaction to a Pub/Sub message is being called after receiving its message. `send` and `receive` are …
> Introducing hooks

- src/Database/Redis/ConnectionContext.hs
Problem Statement: In an application deployed in my organisation, we were seeing an increased time to connect to redis, when we increased the value of `connectTimeout`.
Reason: This was happening because of the higher timeout value which was being passed to `race` in `connect` function as `timeoutOpt`. Function `race` internally calls `cancel` and [cancel](https://hackage.haskell.org/package/async-2.2.4/docs/Control-Concurrent-Async.html#v:cancel) will not terminate until the thread that [Async](https://hackage.haskell.org/package/async-2.2.4/docs/Control-Concurrent-Async.html#t:Async) refers to has been terminated.
Solution : Used [timeout](https://hackage.haskell.org/package/base-4.19.1.0/docs/System-Timeout.html#v:timeout) function instead of `race` to handle that scenario and now it …
> `timeout` instead of `race` to fix async wait time
