- .travis.yml
Not sure if you want this to use stack instead of cabal?
> Add updated travis configuration file.

- codegen/GenCmds.hs
- codegen/commands.json
- src/Database/Redis/Commands.hs
- test/Test.hs
* Add the PF* commands
* Add unit tests
* Remove useless spaces by the way
> Fix #30: Introduce HyperLogLog bindings

- src/Database/Redis/ProtocolPipelining.hs
This should make at least give more expected result for situation described in #36   - the thing is that we should wrap closed handle exception into the library's `ConnectionClosedException`
> All socket io errors assumed to give ConnectionLost

- hedis.cabal
- src/Database/Redis/Core.hs
- src/Database/Redis/Protocol.hs
- src/Database/Redis/PubSub.hs
- src/Database/Redis/Transactions.hs
- src/Database/Redis/Types.hs
Also clean-up some warnings.
Fixes #47.
> Add NFData instances

- src/Database/Redis/ProtocolPipelining.hs
> Rethrow errors

- hedis.cabal
- src/Database/Redis/PubSub.hs
- src/Database/Redis/Types.hs
- test/Test.hs
Hopefully this will help us investigate hanging travis builds.
> Improve failing in tests

- TODO.md
- hedis.cabal
- src/Database/Redis/Core.hs
- src/Database/Redis/ProtocolPipelining.hs
- test/Test.hs
See commit messages for details. This is a non-breaking change, so a minor version bump is sufficient.
> Rewrite of automatic pipelining and performance improvement.

- src/Database/Redis/ProtocolPipelining.hs
This addresses 1st part of #34
> Connection handle should be closed on connect error

- src/Database/Redis/Protocol.hs
The first byte in reply specifies reply type, e.g. '+' is a string.
Before the commit, parser was implemented using backtracking, but
it is completely unnecessary. Now we read the first byte and then
call a particular parser by hands.
The result of the patch is noticeable improvement of parser speed
and 8% decrease of allocations in the benchmark. Before:
```
ping                  145971.76 Req/s
get                   133020.47 Req/s
mget                   94684.51 Req/s
ping (pipelined)     1007272.51 Req/s
multiExec get 1        93903.06 Req/s
multiExec get 50      560180.15 Req/s
multiExec get 1000    572504.88 Req/s
6,115,428,248 bytes allocated in the heap
209,206,824 bytes copied during GC
6,261,232 bytes maximum residency (48 sample(s))
821,264 bytes maximum slop
15 MB total memory …
```
> Improve reply parser performance

- codegen/GenCmds.hs
- src/Database/Redis/Commands.hs
- src/Database/Redis/ManualCommands.hs
- test/Test.hs
> Zrangebylex

- src/Database/Redis/Types.hs
> support for doubles in exponential format

- codegen/GenCmds.hs
- src/Database/Redis.hs
- src/Database/Redis/Commands.hs
- src/Database/Redis/Core.hs
Implemented changes as discussed in issue #79. CI should build properly now :|
> Implemented checkedConnect function

- hedis.cabal
resolves https://github.com/informatikr/hedis/issues/84
> clarify supported versions of redis

- src/Database/Redis/ProtocolPipelining.hs
> Solving #92

- src/Database/Redis/ProtocolPipelining.hs
As mentioned in merge request [#93](https://github.com/informatikr/hedis/pull/93), proposed fix is a bit verbose and should be refactored to avoid code duplication. This PR reverts to using `Network.connectTo` as it was pre [eba98e1](https://github.com/informatikr/hedis/commit/eba98e1eee8923b2f553df181903e8aef05cdf88) except for the AF_INET socket family type, which then gets the special option necessary for faster server connection disconnect detection.
Heads up to @alcidesv to keep him in the loop.
Thx!
Erick
> Refactor fix for issue #92 - (Connection to Unix sockets is broken)

- src/Database/Redis/Commands.hs
- src/Database/Redis/ManualCommands.hs
- test/Test.hs
This is an attempt at implementing the various streams commands. I'm not a Haskell expert so let me know if there's anything that needs changing.
I've tested this against Redis 5.0-RC4.
Closes #111
> Implement streams commands

- .travis.yml
- CHANGELOG
- hedis.cabal
- src/Database/Redis/ManualCommands.hs
- test/Test.hs
> Remove slave-thread dependency

- src/Database/Redis/Core.hs
> Derive MonadFail for the Redis monad

- src/Database/Redis/ProtocolPipelining.hs
Fix for [Leaking sockets when connect fails #143](https://github.com/informatikr/hedis/issues/143)
> [#143] Fixed leaking sockets

- codegen/commands.json
- src/Database/Redis/Commands.hs
- test/Test.hs
> Make HSET return integer instead of bool

- src/Database/Redis/Sentinel.hs
> Fix GHC 8.0.1 compat

- .travis.yml
- src/Database/Redis/ManualCommands.hs
- test/Test.hs
> travis: Upgrade to Redis 6.0.9 & Fix auth test

- .gitignore
- .travis.yml
- CHANGELOG
- hedis.cabal
- src/Database/Redis.hs
- src/Database/Redis/Cluster.hs
- src/Database/Redis/Cluster/Command.hs
- src/Database/Redis/Cluster/HashSlot.hs
- src/Database/Redis/Commands.hs
- src/Database/Redis/Connection.hs
- src/Database/Redis/ConnectionContext.hs
- src/Database/Redis/Core.hs
- src/Database/Redis/ManualCommands.hs
- src/Database/Redis/ProtocolPipelining.hs
- src/Database/Redis/PubSub.hs
- src/Database/Redis/URL.hs
- stack.yaml
- test/ClusterMain.hs
- test/Main.hs
- test/Tests.hs
This is a continuation of @alexjg's work in #142. It contains some bug fixes, passes all tests, and is up to date with this repo's master.
> Ready for review: Clustering Implementation - continuation

- src/Database/Redis/ManualCommands.hs
When Redis stream does not contain any entry fields 'first-entry' and 'last-entry' fields may be missing. Before this patch hedis failed to read a response and filed with `Bulk Nothing` exception.
In this patch we provide a means to support that by introducing an extra constructor to the XInfoStreamResponse. We introduced a constructor instead of wrapping fields into Maybe, because this change leads to a fewer refactoring and in addition in maintains an invariant that the first and the last entries are either full or empty simultaneously.
Fixes #173.
This commit break backwards compatibility, but it seems that the current solution
is the smallest possible breakage we could find
> Support cases when response of xstreamInfo does not contain entries.

- hedis.cabal
- src/Database/Redis/Core/Internal.hs
Simple PR adding a ``MonadUnliftIO`` instance for the ``Redis`` monad. Closes ##180.
> Add MonadUnliftIO instance

- .github/workflows/test.yml
- DocTest.hs
- benchmark/Benchmark.hs
- hedis.cabal
- src/Database/Redis/ManualCommands.hs
- src/Database/Redis/URL.hs
Also fixes a few issues preventing the code from compiling. Removed the `DocTest.hs` executable since it isn't necessary with `--with-ghc=doctest`.
> Add Github Actions

- .github/workflows/test.yml
- src/Database/Redis/Commands.hs
- src/Database/Redis/Connection.hs
- src/Database/Redis/ManualCommands.hs
- src/Database/Redis/ProtocolPipelining.hs
This MR fixes some warnings that we have during compilation and that breaks CI builds.
> This MR fixes warnings and compilation on ghc 9.6

- src/Database/Redis/Cluster/HashSlot.hs
keyToSlot function contained several bugs, so it didn't work according to the spec and the values didn't  match result of the CLUSTER KEYSLOT command.
In this commit we fix those bugs:
1. Now tags are properly matched;
2. Non matching tags return key calculated on entire string;
3. First matching tag is used.
All the cases were tested with CLUSTER KEYSLOT command and added to the doctests.  Unfortunatly it's not added to the full featured testsuite because running CLUSTR KEYSLOT command requirs running redis cluster
Fixes #203.
> Fix keyToSlot function.

- src/Database/Redis/Connection.hs
- Fixed typos and missing imports.
- Switched around the conditional compilation branches. `MIN_VERSION` is true when the version is greater than or equal to the one specified.
- Switched to `newPool` for all versions of `resource-pool >= 0.3.0.0`.
Verified with`cabal build --constraint "resource-pool >=0.2 && < 0.3"` and `cabal build --constraint "resource-pool >= 0.4"`.
> Fix resource pool conditional compilation

- .github/workflows/test.yml
This PR tries to run tests that requires Redis in CI
> Add GitHub actions driven Redis tests
